整理合并新代码
Beijing-Vision-911/lens_editor pull request #12
Opened 2023-01-06 09:17 UTC by Lxcall

#11

2023-01-06 11:52 UTC, peterzky commented
@14649 无用的PR可以直接关闭

2023-01-09 02:26 UTC, peterzky commented
是否可以合并?

2023-01-09 03:11 UTC, 14649 requested changes

2023-01-09 03:11 UTC, 14649 commented on lens_editor/defect.py
> +        self.pixmap1 = numpy2pixmap(self.defect.lens.img.copy())  # ,(r_w*15,r_h*15
```suggestion
        self.pixmap1 = numpy2pixmap(self.defect.lens.img.copy())  # ,(r_w*15,r_h*15
```
删除无用的注释

2023-01-09 05:20 UTC, merged