Feat minimap
Beijing-Vision-911/lens_editor pull request #3
Opened 2022-09-21 11:19 UTC by G-87

2022-09-21 11:41 UTC, peterzky requested changes
需要继续修改

2022-09-21 11:41 UTC, peterzky commented on lens_editor/__init__.py
> +VERSION = '0.10.0'
这是我修改为了给你演示用的, 提交之前请修改回原来的版本

2022-09-21 11:41 UTC, peterzky commented on lens_editor/defect.py
> +            if  y_t + tooltip.shape[0] > 1220:
这两个为什么要分开判断?

2022-09-21 11:41 UTC, peterzky commented on lens_editor/defect.py
> +        else:
之前我和你说的解决办法是不是没听明白?

2022-09-26 06:09 UTC, G-87 commented on lens_editor/defect.py
> +            if  y_t + tooltip.shape[0] > 1220:
因为当时想添加别的条件

2022-09-26 06:09 UTC, G-87 commented on lens_editor/__init__.py
> +VERSION = '0.10.0'
好的

2022-09-26 06:10 UTC, G-87 commented on lens_editor/defect.py
> +        else:
是的

2022-09-26 13:04 UTC, closed without merging